version: '3'
services:
  db:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
    expose:
      - '3306'
    volumes:
      - b33r-db:/var/lib/mysql
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/b33rtime
    ports:
      - "3000:3000"
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpacker
    depends_on:
      - db

  webpacker:
    build: .
    env_file:
      - '.env.docker'
    command: ./bin/webpack-dev-server
    volumes:
      - .:/b33rtime
    ports:
      - '3035:3035'

volumes:
  b33r-db:
