version: '3.9'
services:
  db:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
    expose:
      - '3306'
    ports:
      - '3306:3306'
    volumes:
      - b33r-db:/var/lib/mysql
  web:
    build: .
    depends_on:
      - vite
      - db
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/b33rtime
    ports:
      - "3000:3000"
    environment:
      VITE_RUBY_HOST: vite
      RAILS_ENV: development
  vite:
    build: .
    command: bundle exec vite dev
    environment:
        DEBUG: '*vite*'
        RAILS_ENV: development
        VITE_RUBY_HOST: 0.0.0.0
    volumes:
      - .:/b33rtime
    ports:
      - '3036:3036'
    expose:
      - '3036'
volumes:
  b33r-db:
