version: '3.9'
services:
  postgres:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - b33r-postgres-db:/var/lib/postgresql/data
  web:
    build: .
    depends_on:
      - vite
      - postgres
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/b33rtime
    ports:
      - "3000:3000"
    environment:
      VITE_RUBY_HOST: vite
      RAILS_ENV: development
  vite:
    build: .
    command: bundle exec vite dev
    environment:
        DEBUG: '*vite*'
        RAILS_ENV: development
        VITE_RUBY_HOST: 0.0.0.0
    volumes:
      - .:/b33rtime
    ports:
      - '3036:3036'
    expose:
      - '3036'
volumes:
  b33r-postgres-db:
